"""empty message

Revision ID: 28b3e181fa6e
Revises: bbf4f5756e67
Create Date: 2021-09-04 01:39:16.475965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b3e181fa6e'
down_revision = 'bbf4f5756e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('bio', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'bio')
    # ### end Alembic commands ###
