"""empty message

Revision ID: 311e75e2ebd8
Revises: e3b7e2a958b9
Create Date: 2021-09-13 00:59:23.929484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311e75e2ebd8'
down_revision = 'e3b7e2a958b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
