"""empty message

Revision ID: e3b7e2a958b9
Revises: 23b69ae4b627
Create Date: 2021-09-11 00:30:03.985481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b7e2a958b9'
down_revision = '23b69ae4b627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('auto_update', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'auto_update')
    # ### end Alembic commands ###
