"""empty message

Revision ID: fa5b4ed921bf
Revises: cf02a0fad894
Create Date: 2021-09-22 20:30:00.023365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5b4ed921bf'
down_revision = 'cf02a0fad894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'date')
    # ### end Alembic commands ###
